import {BaseModule} from '../../Common/BaseModule';

export interface HrEmployee extends BaseModule<number> {
    firstName: string;
    lastName: string;
    middleName: string;
    gender: boolean;
    dateOfBirth: string;
    nationalityID: number;
    maritalStatusID: number;
    phoneNumber: string;
    email: string;
    address: string;
    cityID: number;
    state: string;
    zipCode: string;
    employeeCode: string;
    jobID: number;
    departmentID: string;
    dateOfJoining: string;
    dateOfResignation: string | null;
    employmentTypeID: number;
    workLocationID: number;
    salary: number;
    bankName: string;
    bankAccountNumber: string;
    iBAN: string;
    directDeposit: boolean;
    supervisorID: number;
    isActive: boolean;
    isTerminated: boolean;
    terminationDate: string | null;
    terminationReason: string;
    annualLeaveDays: number;
    sickLeaveDays: number;
    takenLeaveDays: number;
    grossSalary: number;
    netSalary: number;
    taxAmount: number;
    totalDeductions: number;
    totalAllowance: number;
    branchID: number;
    jobDescription: string;
    iDNo: string;
    iDIssuerName: string;
    iDIssuerDate: string | null;
    iDExpireDate: string | null;
    passportNo: string;
    passIssuerDate: string | null;
    passExpireDate: string | null;
    empPhotoUrl: string;
    contractTypeID: number;
    dateOfAppointment: string | null;
}